name: CI/CD Pipeline for Container Deployment

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Build and test with Gradle
        run: ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t grovince/c-keeper:account-t${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push grovince/c-keeper:account-t${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to Server and Pull Docker Image
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          script: |
            docker pull grovince/c-keeper:account-t${{ github.sha }}
            kubectl set image deployment/backend-account-deployment backend-account=grovince/c-keeper:account-t${{ github.sha }}